---
title: "5) Colors"
date: "`r Sys.time()`"
date-format: "ddd, D of MMMM, YYYY"
date-modified: last-modified
lang: en
editor: source
engine: knitr
#editor: source
## ------  general Output Options
execute:     
  eval: false    # run the code ? 
  echo: true     #  include source code in output?
  warning: false  #  include warning code in output
  error: false    #  include error code in output
  output: false   # include output code in output (CHG in BLOCKS)
  # include: false   # R still runs but code and results DON"T appear in output  
  cache: false # normalmnte false
toc: true
fig-cap-location: top
tbl-cap-location: top
format:
  html:
    # theme: flatly #spacelab
    code-fold: false # redundant bc echo false 
    toc-depth: 3
    toc_float: true
    toc-location: left
    toc-title: Outline
    embed-resources: true # external dependencies embedded (Not in ..._files/)
  # pdf:
  #   toc-depth: 2
  #   toc-title: Indice
  #   highlight-style: github
  #   #lang: it
  #   embed-resources: true # external dependencies embedded (Not in ..._files/)
format-links: false
---

::: {.callout-caution collapse="false"}
Web page construction in progress...
:::


## Colors

 
```{r}
pacificharbour_shades <- c( "#d4e6f3","#b8d6eb", "#9cc6e3", "#80b6db",  "#72aed8", "#5b8bac", "#39576c",  "#16222b")

pacificharbour  <- "#72aed8"
japyew <- "#d89c72"
triad_verde <- "#d8cf71"
triad_rosso <- "#d8717b"

bluMEFprinc <- "#2D337C" # "#2D337CFF" (alpha = 1) OR rgb(45/255, 51/255, 124/255, 1)
bluMEFsec <- "#455A8B" # "#455A8BFF" (alpha = 1) OR rgb(69/255, 90/255, 139/255, 1)
bluMEFsec_light <- "#455A8B99"
bluMEFsec_extralight <- "#455A8B33" #  (alpha = .2) OR rgb(69/255, 90/255, 139/255, .2)

gialloMEF_dark <- "#715115"
gialloMEFprinc <- "#BD8723" # "#BD8723FF" (alpha = 1) OR rgb(189/255, 135/255, 35/255, 1)
gialloMEF_light <- "#d7b77b" # "#BD8723FF" (alpha = 1) OR rgb(189/255, 135/255, 35/255, 0.4)
gialloMEF_extralight <- "#f1e7d3" # "#BD8723FF" (alpha = 1) OR rgb(189/255, 135/255, 35/255, 0.2)

bordeaux_dark <- "#51242c" # "#854442FF" (alpha = 1) OR rgb(133/255, 68/255, 66/255, 1)
bordeaux <- "#873c4a" # "#854442FF" (alpha = 1) OR rgb(133/255, 68/255, 66/255, 1)
bordeaux_light <- "#b78a92" #"#85444299"
bordeaux_extralight <- "#e7d8da" #" "#e6cdcc"

viola <- "#2D337C"
viola_light <- "#8e94d6" #"#85444299"
viola_extralight <- "#d9dbf1" #" "#e6cdcc"

verde_dark <- "#245048"
verde <- "#3c8678" # "#285E60FF" (alpha = 1) OR rgb(40/255, 94/255, 96/255, 1)
verde_light <- "#8ab6ae" # "#285E60FF" (alpha = 1) OR rgb(40/255, 94/255, 96/255, 1)
verde_extralight <- "#d8e6e4"
verdino <- "#a6bd23"

marrone_dark  <- "#5d2b15"
marrone <- "#9b4923" # "#866445FF" (alpha = 1) OR rgb(134/255, 100/255, 69/255, 1)
marrone_light <- "#c3917b"
marrone_extralight <- "#ebdad3"

grigio_scuro <- "#4c4c4c" # "#A6A6A6FF" (alpha = 1) OR rgb(166/255, 166/255, 166/255, 1)
grigio <- "#A6A6A6"
grigioSfondo <- "#F2F2F2" # "#F2F2F2FF" (alpha = 1) OR rgb(242/255, 242/255, 242/255, 1)


arancio_dark  <- "#8e550a"
arancio <- "#bd710e" # "#866445FF" (alpha = 1) OR rgb(134/255, 100/255, 69/255, 1)
arancio_light <- "#f0a441"
arancio_extralight <- "#fbe8cf"

rosso <- "#9b2339"
# col2rgb( "#854442")
```



## Color palettes 

```{r}
#palette_g20 <- c("#455A8B", "#854442", "#285E60", "#BD8723", "#866445", "#A6A6A6")
#mycolors_gradient <- c("#ccf6fa", "#80e8f3", "#33d9eb", "#00d0e6", "#0092a1")

#                   fat gold  |Romaine Green| Blue ColaD |directoire Blue| Bourgeois  | Aztec Turquoise | Fulvous
mycolors_contrast <- c("#9b2339", "#E7B800","#239b85", "#85239b", "#9b8523","#23399b", "#d8e600", "#0084e6","#399B23",  "#e60066" , "#00d8e6",  "#005ca1", "#e68000")
#theme_col <-  c("#00d7e6", "#0065e6",  "#10069f")  
three_col <- c("#d8e600", "#e68000",  "#e60c00")     
two_col <- c( "#009E73","#E69F00")

two_col_contrast <- c( "#399B23",  "#e60066" )


blu_contrast <- c(
  "#0f7184",
  "#56adbf",
  "#5bd6ef",
  "#025b6d",
  "#b5f2ff",
  "#1b5884",
  "#72aed8",
  "#98c8ea",
  "#5097c9",
  "#3a7aa8",
  "#0286e5",
  "#c6e7ff",
  "#013d68"
  )
  

 
```



```{r}
# # -- Add custom fonts & make custom theme for ggplot2 -----
# # -- da google
sysfonts::font_add_google(name = "Roboto Condensed", family =  "Condensed")
sysfonts::font_add(family = "Roboto Condensed", regular =  "~/Applications/Roboto_Condensed/RobotoCondensed#-Regular.ttf")
# # -- da web
sysfonts::font_add(family = "Inconsolata", regular = "~/Applications/Inconsolata/static/Inconsolata_Expanded#.ttf")
sysfonts::font_families()
# 
# # install.packages("extrafont")
library(extrafont)
# # -- quali ho nel sistema
fonts()
# # -- Import all the .ttf files from your system
```